### ISSUE TITLE
[coursera] first annotation dialog cut off

### ISSUE THREAD

**Issue by rahuljayaraman** [activesphere/video-annotation#1]
Steps:
Open https://www.coursera.org/learn/machine-learning/lecture/V9MNG/problem-motivation
Press Alt-e to open new annotation.

Observed:
The dialog box is cut off.

<img width="485" alt="screen shot 2016-02-14 at 1 14 28 pm" src="https://cloud.githubusercontent.com/assets/1269539/13032595/09141eea-d31f-11e5-9465-b752cd45184a.png">

Cancel & press Alt-E again.
Now, seems to work correctly

**Comment by dgp** [comment]
Fixed
