### ISSUE TITLE
position of dialog's pointer when video starts is off

### ISSUE THREAD

**Issue by rahuljayaraman** [activesphere/video-annotation#2]
Steps:
Open any coursera/youtube video.
Press Alt-E at 00:00

Observed:
Positioning of the dialog's timeline pointer is off

<img width="413" alt="screen shot 2016-02-14 at 1 24 57 pm" src="https://cloud.githubusercontent.com/assets/1269539/13032631/e61c87dc-d31f-11e5-9c4c-72ecaaa7c9da.png">

**Comment by dgp** [comment]
Fixed
